CREATE TABLE t(x INTEGER PRIMARY KEY ASC, y, z);
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1000000)
INSERT INTO t (y,z)
SELECT x as x, x as y FROM cnt;
CREATE VIEW select_t AS SELECT * FROM t ORDER BY z DESC LIMIT 100;
SELECT 'first',* FROM (SELECT * FROM t ORDER BY y ASC, z ASC LIMIT 10)
UNION 
SELECT 'last',* FROM (SELECT * FROM t ORDER BY y DESC, z DESC LIMIT 10);
SELECT 'first',* FROM (SELECT * FROM t ORDER BY ROWID ASC LIMIT 10)
UNION 
SELECT 'last',* FROM (SELECT * FROM t ORDER BY ROWID DESC LIMIT 10);